# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-05-23 13:10:03
"""
import arcpy

def Model1():  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    BPI_Broad = arcpy.Raster("Z:\\Isla_MSc_Ch1\\Geodatabases\\Isla_MSc_Ch1.gdb\\BPI_Broad")
    BPI_Fine = arcpy.Raster("Z:\\Isla_MSc_Ch1\\Geodatabases\\Isla_MSc_Ch1.gdb\\BPI_Fine")

    # Process: Standardize BPIs (Standardize BPIs) (btm)
    BPI_Broad_Std = "Z:\\Isla_MSc_Ch1\\Geodatabases\\Isla_MSc_Ch1.gdb\\BPI_Broad_Std"
    BPI_Fine_Std = "Z:\\Isla_MSc_Ch1\\Geodatabases\\Isla_MSc_Ch1.gdb\\BPI_Fine_Std"
    arcpy.btm.standardizebpi(Broad_BPI_raster=BPI_Broad, Broad_BPI_Mean=0.155891366051146, Broad_BPI_Standard_deviation=1.19084979397663, Output_broad_raster=BPI_Broad_Std, Fine_BPI_raster=BPI_Fine, Fine_BPI_Mean=2.11827029720677E-02, Fine_BPI_Standard_deviation=0.197285409260073, Output_fine_raster=BPI_Fine_Std)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\islat\\Documents\\ArcGIS\\Projects\\SeafloorMorphology_ModelToPython\\SeafloorMorphology_ModelToPython.gdb", workspace="C:\\Users\\islat\\Documents\\ArcGIS\\Projects\\SeafloorMorphology_ModelToPython\\SeafloorMorphology_ModelToPython.gdb"):
        Model1()
